enum ThreadSystem { unc, unf, metric }

class ThreadSpec {
  final ThreadSystem system;
  // for disaplay and dropdowns
  final String label;

  // in for unc/unf
  final double major;

  //TPI for unc/unf, pitch
  final double pitchOrTpi;

  const ThreadSpec({
    required this.system,
    required this.label,
    required this.major,
    required this.pitchOrTpi,
  });
}

const List<ThreadSpec> commonUNC = [
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#1-64",
    major: 0.0730,
    pitchOrTpi: 64,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#2-56",
    major: 0.0860,
    pitchOrTpi: 56,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#3-48",
    major: 0.0990,
    pitchOrTpi: 48,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#4-40",
    major: 0.1120,
    pitchOrTpi: 40,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#5-40",
    major: 0.1250,
    pitchOrTpi: 40,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#6-32",
    major: 0.1380,
    pitchOrTpi: 32,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#8-32",
    major: 0.1640,
    pitchOrTpi: 32,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#10-24",
    major: 0.1900,
    pitchOrTpi: 24,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "#12-24",
    major: 0.2160,
    pitchOrTpi: 24,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1/4-20",
    major: 0.2500,
    pitchOrTpi: 20,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "5/16-18",
    major: 0.3125,
    pitchOrTpi: 18,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "3/8-16",
    major: 0.3750,
    pitchOrTpi: 16,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "7/16-14",
    major: 0.4375,
    pitchOrTpi: 14,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1/2-13",
    major: 0.5000,
    pitchOrTpi: 13,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "9/16-12",
    major: 0.5625,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "5/8-11",
    major: 0.6250,
    pitchOrTpi: 11,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "3/4-10",
    major: 0.7500,
    pitchOrTpi: 10,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "7/8-9",
    major: 0.8750,
    pitchOrTpi: 9,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1-8",
    major: 1.0000,
    pitchOrTpi: 8,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1-1/8-7",
    major: 1.1250,
    pitchOrTpi: 7,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1-1/4-7",
    major: 1.2500,
    pitchOrTpi: 7,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1-3/8-6",
    major: 1.3750,
    pitchOrTpi: 6,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1-1/2-6",
    major: 1.5000,
    pitchOrTpi: 6,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "1-3/4-5",
    major: 1.7500,
    pitchOrTpi: 5,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "2-4.5",
    major: 2.0000,
    pitchOrTpi: 4.5,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "2-1/4-4.5",
    major: 2.2500,
    pitchOrTpi: 4.5,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "2-1/2-4",
    major: 2.5000,
    pitchOrTpi: 4,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "2-3/4-4",
    major: 2.7500,
    pitchOrTpi: 4,
  ),
  ThreadSpec(
    system: ThreadSystem.unc,
    label: "3-4",
    major: 3.0000,
    pitchOrTpi: 4,
  ),
];
const List<ThreadSpec> commonUNF = [
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#0-80",
    major: 0.0600,
    pitchOrTpi: 80,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#1-72",
    major: 0.0730,
    pitchOrTpi: 72,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#2-64",
    major: 0.0860,
    pitchOrTpi: 64,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#3-56",
    major: 0.0990,
    pitchOrTpi: 56,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#4-48",
    major: 0.1120,
    pitchOrTpi: 48,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#5-44",
    major: 0.1250,
    pitchOrTpi: 44,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#6-40",
    major: 0.1380,
    pitchOrTpi: 40,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#8-36",
    major: 0.1640,
    pitchOrTpi: 36,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#10-32",
    major: 0.1900,
    pitchOrTpi: 32,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "#12-28",
    major: 0.2160,
    pitchOrTpi: 28,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1/4-28",
    major: 0.2500,
    pitchOrTpi: 28,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "5/16-24",
    major: 0.3125,
    pitchOrTpi: 24,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "3/8-24",
    major: 0.3750,
    pitchOrTpi: 24,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "7/16-20",
    major: 0.4375,
    pitchOrTpi: 20,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1/2-20",
    major: 0.5000,
    pitchOrTpi: 20,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "9/16-18",
    major: 0.5625,
    pitchOrTpi: 18,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "5/8-18",
    major: 0.6250,
    pitchOrTpi: 18,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "3/4-16",
    major: 0.7500,
    pitchOrTpi: 16,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "7/8-14",
    major: 0.8750,
    pitchOrTpi: 14,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1-12",
    major: 1.0000,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1-1/8-12",
    major: 1.1250,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1-1/4-12",
    major: 1.2500,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1-3/8-12",
    major: 1.3750,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1-1/2-12",
    major: 1.5000,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "1-3/4-12",
    major: 1.7500,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "2-12",
    major: 2.0000,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "2-1/4-12",
    major: 2.2500,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "2-1/2-12",
    major: 2.5000,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "2-3/4-12",
    major: 2.7500,
    pitchOrTpi: 12,
  ),
  ThreadSpec(
    system: ThreadSystem.unf,
    label: "3-12",
    major: 3.0000,
    pitchOrTpi: 12,
  ),
];

const List<ThreadSpec> commonMetric = [
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M2 x 0.4",
    major: 2.0,
    pitchOrTpi: 0.4,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M2.5 x 0.45",
    major: 2.5,
    pitchOrTpi: 0.45,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M3 x 0.5",
    major: 3.0,
    pitchOrTpi: 0.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M3 x 0.35",
    major: 3.0,
    pitchOrTpi: 0.35,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M4 x 0.7",
    major: 4.0,
    pitchOrTpi: 0.7,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M4 x 0.5",
    major: 4.0,
    pitchOrTpi: 0.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M5 x 0.8",
    major: 5.0,
    pitchOrTpi: 0.8,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M5 x 0.5",
    major: 5.0,
    pitchOrTpi: 0.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M6 x 1.0",
    major: 6.0,
    pitchOrTpi: 1.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M6 x 0.75",
    major: 6.0,
    pitchOrTpi: 0.75,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M8 x 1.25",
    major: 8.0,
    pitchOrTpi: 1.25,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M8 x 1.0",
    major: 8.0,
    pitchOrTpi: 1.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M10 x 1.5",
    major: 10.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M10 x 1.25",
    major: 10.0,
    pitchOrTpi: 1.25,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M12 x 1.75",
    major: 12.0,
    pitchOrTpi: 1.75,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M12 x 1.5",
    major: 12.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M14 x 2.0",
    major: 14.0,
    pitchOrTpi: 2.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M14 x 1.5",
    major: 14.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M16 x 2.0",
    major: 16.0,
    pitchOrTpi: 2.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M16 x 1.5",
    major: 16.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M18 x 2.5",
    major: 18.0,
    pitchOrTpi: 2.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M18 x 1.5",
    major: 18.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M20 x 2.5",
    major: 20.0,
    pitchOrTpi: 2.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M20 x 1.5",
    major: 20.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M22 x 2.5",
    major: 22.0,
    pitchOrTpi: 2.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M22 x 1.5",
    major: 22.0,
    pitchOrTpi: 1.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M24 x 3.0",
    major: 24.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M24 x 2.0",
    major: 24.0,
    pitchOrTpi: 2.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M27 x 3.0",
    major: 27.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M27 x 2.0",
    major: 27.0,
    pitchOrTpi: 2.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M30 x 3.5",
    major: 30.0,
    pitchOrTpi: 3.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M30 x 2.0",
    major: 30.0,
    pitchOrTpi: 2.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M33 x 3.5",
    major: 33.0,
    pitchOrTpi: 3.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M33 x 2.0",
    major: 33.0,
    pitchOrTpi: 2.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M36 x 4.0",
    major: 36.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M36 x 3.0",
    major: 36.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M39 x 4.0",
    major: 39.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M39 x 3.0",
    major: 39.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M42 x 4.5",
    major: 42.0,
    pitchOrTpi: 4.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M42 x 3.0",
    major: 42.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M45 x 4.5",
    major: 45.0,
    pitchOrTpi: 4.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M45 x 3.0",
    major: 45.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M48 x 5.0",
    major: 48.0,
    pitchOrTpi: 5.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M48 x 3.0",
    major: 48.0,
    pitchOrTpi: 3.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M52 x 5.0",
    major: 52.0,
    pitchOrTpi: 5.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M52 x 4.0",
    major: 52.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M56 x 5.5",
    major: 56.0,
    pitchOrTpi: 5.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M56 x 4.0",
    major: 56.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M60 x 5.5",
    major: 60.0,
    pitchOrTpi: 5.5,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M60 x 4.0",
    major: 60.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M64 x 6.0",
    major: 64.0,
    pitchOrTpi: 6.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M64 x 4.0",
    major: 64.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M68 x 6.0",
    major: 68.0,
    pitchOrTpi: 6.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M68 x 4.0",
    major: 68.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M72 x 6.0",
    major: 72.0,
    pitchOrTpi: 6.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M72 x 4.0",
    major: 72.0,
    pitchOrTpi: 4.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M76 x 6.0",
    major: 76.0,
    pitchOrTpi: 6.0,
  ),
  ThreadSpec(
    system: ThreadSystem.metric,
    label: "M76 x 4.0",
    major: 76.0,
    pitchOrTpi: 4.0,
  ),
];
